### ISSUE TITLE
Checkpoint for folder

### ISSUE THREAD

**Issue by Izzzzy** [micnil/vscode-checkpoints#11]
Can I add a checkpoint for an entire folder, or must it be added per file?

**Comment by micnil** [comment]
Only per file unfortunately. Not sure I'd find adding a folder too useful. The times I would want to add multiple files as a checkpoint I probably want to use git.

**Comment by Izzzzy** [comment]
@micnil Thank you. I'm using git, just sometimes when I'm not ready to commit (e.g. my code is messy but it works), I want to be able to clean up and be able to track my changes in case I break something in the process. Is that possible with git?

**Comment by micnil** [comment]
Well, if I was in that situation I probably would do a: `git stash && git stash apply` (which will put everything is stash and then reapply it directly after). You could also do it for individual files or folders. An alternative way is to add the files to staging and then `git stash --keep-index`. As you maybe know, you could also give the stash a name by running `git stash save <message>` :)

stackoverflow:
[Stash changes while keeping the changes in the working directory in Git](https://stackoverflow.com/questions/17843384/stash-changes-while-keeping-the-changes-in-the-working-directory-in-git)

**Comment by Izzzzy** [comment]
@micnil Thank you very much. That looks like what I need.
