### ISSUE TITLE
checkpoint keep showing in SCM

### ISSUE THREAD

**Issue by aolba** [micnil/vscode-checkpoints#12]
Checkpoint keep appearing in SCM panel, even when I have set to show in explorer.
CHECKPOINT version 1.2.0
VS version data:

Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by micnil** [comment]
That seems bad, will give it a look soon!

**Comment by micnil** [comment]
No really "soon", but I believe this should be fixed now. Version 1.3.0 published. Thanks for your report!
