### ISSUE TITLE
Diff w Current does not work...

### ISSUE THREAD

**Issue by ambicoder** [micnil/vscode-checkpoints#22]
After updating to VSCode 1.67.1 the command Diff W Current does not work...

**Comment by aolba** [comment]
Same issue with the same vscode version.
Checkpoint version v1.3.2

**Comment by micnil** [comment]
Thanks so much for reporting @ambicoder @aolba! I just published a patch with a fix: v1.3.3

**Comment by ambicoder** [comment]
Thanks a lot...your extension is very helpful in my progects

**Comment by aolba** [comment]
Thank you for check on this @micnil .

**Comment by karabatak2516** [comment]
/

**Comment by karabatak2516** [comment]
@ @aolba 

> 

1. > 

- [x]   ##``
