### ISSUE TITLE
where are the checkpoints stored ?

### ISSUE THREAD

**Issue by lepinekong** [micnil/vscode-checkpoints#3]
Hi, love this extension. Would like to know where they are stored. Thanks.

**Comment by micnil** [comment]
Thank you!

The storage mechanism used is internal to vscode and is to my understanding the equivilant of a browsers [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).  The api used is called [ExtensionContext.workspaceState](https://code.visualstudio.com/docs/extensionAPI/vscode-api#1199) and is a "[Memento](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Memento)" object. I **think** the actual physical local on disk that the data is stored is (on windows): 
_C:\Users\mi-nil\AppData\Roaming\Code\Local Storage._
but the content is not readable. Why do you ask, do you want to have the checkpoints saved to disk?

/Michael

**Comment by micnil** [comment]
I'll close this issue for now @lepinekong. Is having the checkpoints in readable format on disk a useful feaature for you? I might implement this as an option this summer.
