### ISSUE TITLE
Feature request: checkpoints panel in "Source control" tab instead of "Explorer"

### ISSUE THREAD

**Issue by tomaskikutis** [micnil/vscode-checkpoints#4]
Thanks for the great extension! I'd like to be able to configure the extension to appear in "Source control" tab instead of "Explorer".

**Comment by micnil** [comment]
ooh, that's a good idea. Will take a look this weekend.

**Comment by tomaskikutis** [comment]
Awesome, thanks :)

**Comment by micnil** [comment]
Fixed in daff163.

There is now a new config to show the checkpoints panel in source control: `checkpoints.showCheckpointsInScm`.

I considered removing the "showCheckpointsIn*" configs altogether since I noticed that VS code now has this built in by right clicking the panel and unchecking the extension. But I decided to keep it as is for the time being, so that everyone doesn't get this enabled by default. Also, the built in command is global, and maybe one might want to hide the checkpoints panel per workspace.

Anyway, just scribbling my thought, let me know if any problems arises from this.

**Comment by tomaskikutis** [comment]
Thanks for the fix, works great.

Unrelated note: I was trying to use the extension in my workflow, but noticed it didn't support multiple files.

If I were to put in the time into building a similar thing I'd probably build a smart stash manager instead(group stashes by branch, enable tags and filtering).

I'm wondering what was the use case you built the extension for? Why didn't you build it on top of git stashes? Do you use other version control system than git?

**Comment by micnil** [comment]
I did consider this, and to be honest I don't quite remember my complete thinking. 

I think the main reason is actually that this was easier and served my purpose. It also comes with a couple of nice benefits.

1. I can use it both at home and work (use git at home, mercurial at work)
2. I can use it on ignored files. I have used this quite extensively when mixturing with config files in integrated systems and .env files. Also when testing minor adjustments in third party node modules (changing typescript definitions etc.) before reporting an issue or fixing it. 

These are the main scenarios i built the extension for:
1. Testing two different implementations of say a single function.
2. Having a bookmark of my "undo-stack" while working on something complex. Easier to get back to where I was if i notice that I was heading in the wrong direction.
3. As a way to present my thinking to coworkers in a pre-commit review scenario. ("first I did this <restore checkpoint 1>, but I noticed it wasn't very performant, so I changed it to this <restore checkpoint 2>."). This doesn't happen to often though... 

I rarely need this only multiple files, but I definately could see the benefit. If you build that extension let me know 👍

**Comment by tomaskikutis** [comment]
Thanks for elaborating. FIY git stashes work with ignored files as well. Most of your use cases would also work if the extension was built on stashes, except for being VCS independent which might also be useful for some.

As for myself, I've found a nice [stash manager extension](https://marketplace.visualstudio.com/items?itemName=arturock.gitstash) which satisfies me for now :)
