### ISSUE TITLE
Auto creating checkpoints on file save

### ISSUE THREAD

**Issue by brooth** [micnil/vscode-checkpoints#7]
Thanks for the plugin. Would be awesome if it creates checkpoints automatically on file save. Would be the great alternative to local-history which seems abandoned.

**Comment by micnil** [comment]
Sorry for the delay. Sounds like a good idea. I guess you could get behavior like this by changing the keyboard shortcut for "Checkpoints: Add Checkpoint" to Ctrl + S, and disabling setting "Checkpoints: Ask for Checkpoint Name".  

That way, at least you get a checkpoint every time you save with the keyboard, without having the name dialog pop up. Won't work with any auto-saving funtionality though (like when you build).

I think if checkpoints are added this frequently, it might be a good idea to add have a configurable max limit on checkpoints. Either per file or workspace. I'll leave this open for now, hope the shortcut workaround works for you in the meantime.

**Comment by brooth** [comment]
Thanks for the workaround, unfortunately, I don't use shortcuts for saving files, VSCode does this automatically on focus-lost and it works quite well. I'll keep an eye on this issue hope it'll be implemented.

**Comment by liangjiancang** [comment]
> Thanks for the workaround, unfortunately, I don't use shortcuts for saving files, VSCode does this automatically on focus-lost and it works quite well. I'll keep an eye on this issue hope it'll be implemented.

the extension "Local History" offers what you want, but it also has other problems with non-workspace files

**Comment by micnil** [comment]
Thanks to @amiramitai I think we can close this now. From changelog:

> 1.3.2
> Add setting addCheckpointOnSave to create checkpoint when a file is saved. Disabled by default.

Pairs nicely with disabled: askForCheckpointName
